// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(
    '[Sheet Guardian] Supabase não configurado. Configure as variáveis de ambiente:\n' +
    '- VITE_SUPABASE_URL\n' +
    '- VITE_SUPABASE_PUBLISHABLE_KEY\n\n' +
    'No Vercel: Settings > Environment Variables'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock client for when Supabase is not configured
const createMockClient = (): SupabaseClient<Database> => {
  const notConfiguredError = new Error('Supabase não configurado');

  const mockAuth = {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
    signOut: () => Promise.resolve({ error: null }),
    resetPasswordForEmail: () => Promise.resolve({ data: {}, error: notConfiguredError }),
    updateUser: () => Promise.resolve({ data: { user: null }, error: notConfiguredError }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    refreshSession: () => Promise.resolve({ data: { session: null, user: null }, error: notConfiguredError }),
  };

  return {
    auth: mockAuth,
    from: () => ({
      select: () => ({
        eq: () => ({
          maybeSingle: () => Promise.resolve({ data: null, error: notConfiguredError }),
          single: () => Promise.resolve({ data: null, error: notConfiguredError }),
        }),
        maybeSingle: () => Promise.resolve({ data: null, error: notConfiguredError }),
      }),
      update: () => ({
        eq: () => Promise.resolve({ data: null, error: notConfiguredError }),
      }),
      insert: () => Promise.resolve({ data: null, error: notConfiguredError }),
      delete: () => ({
        eq: () => Promise.resolve({ data: null, error: notConfiguredError }),
      }),
    }),
  } as unknown as SupabaseClient<Database>;
};

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMockClient();