// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(
    '[Sheet Guardian] Supabase não configurado. Configure as variáveis de ambiente:\n' +
    '- VITE_SUPABASE_URL\n' +
    '- VITE_SUPABASE_PUBLISHABLE_KEY\n\n' +
    'No Vercel: Settings > Environment Variables'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a mock client for when Supabase is not configured
const createMockClient = (): SupabaseClient<Database> => {
  const mockAuth = {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase não configurado') }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Supabase não configurado') }),
    signOut: () => Promise.resolve({ error: null }),
  };

  return {
    auth: mockAuth,
    from: () => ({
      select: () => ({ eq: () => ({ maybeSingle: () => Promise.resolve({ data: null, error: new Error('Supabase não configurado') }) }) }),
      update: () => ({ eq: () => Promise.resolve({ error: new Error('Supabase não configurado') }) }),
    }),
  } as unknown as SupabaseClient<Database>;
};

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMockClient();